networks:
    nginx-php83-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php83-service
            - mysql8-service
        networks:
            - nginx-php83-mysql8-node

    # php
    php83-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php83-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php83-mysql8-node

    # mysql
    mysql8-service:
        image: mysql:8.0.33
        container_name: mysql8-container
        ports:
            - "4306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD_FILE: password
            MYSQL_USER: root
            MYSQL_PASSWORD_FILE: password
        networks:
            - nginx-php83-mysql8-node
